name: "OpenAI PR Review Debug"

on:
  issue_comment:
    types: [created]

jobs:
  debug-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Dump event info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Is PR?: ${{ github.event.issue.pull_request != null }}"
